<?php

return [
	'login'=>[
		'email'=>[
			'required'=>[]
			,'email'=>[]
			,'exists'=>['consultants,email']
		],'password'=>[
			'required'=>[]
		]
	],'join'=>[
		'email'=>[
			'required'=>[]
			,'email'=>[]
			,'unique'=>['consultants,email']
		],'name'=>[
			'required'=>[]
		],'hourlyMin'=>[
			'required'=>[]
			,'integer'=>[]
			,'between'=>[100,500]
		],'country_id'=>[
			'required'=>[]
		],'zip'=>[
			'required'=>[]
		]
		,'password'=>[
			'required'=>[]
		],'passwordConfirmation'=>[
			'required'=>[]
			,'same'=>['password']
		]	
	],'reset'=>[
		'email'=>[
			'required'=>[]
			,'exists'=>['consultants,email']
		],'password'=>[
			'required'=>[]
		],'passwordConfirmation'=>[
			'required'=>[]
			,'same'=>['password']
		]
	],'user'=>[
		'email'=>[
			'required'=>[]
			,'email'=>[]
			,'mineOrUnique'=>['email']
		]
	],'password'=>[
		'password'=>[
			'required'=>[]
		]
		,'passwordConfirmation'=>[
			'required'=>[]
			,'same'=>['password']
		]
	]
];